### ISSUE TITLE
Search Bar Not Returning Correct Results for Movies, TV Shows, and Manga

### ISSUE THREAD

**Issue by omghante** [SnoozeScript/OtakuHaven#1]
The search bar on the home screen of OtakuHaven, designed to allow users to search for content, is functioning correctly when searching for anime. However, it fails to provide proper results when users search for movies, TV shows, or manga.

The search bar should return accurate and relevant results for all categories: anime, movies, TV shows, and manga.

Accurate results are returned only for anime.
Results for movies, TV shows, and manga are not functioning as intended.

Ensure that the search functionality is configured to filter and retrieve results from the correct datasets or categories.
Check for any potential API or database query issues that might limit the scope of the search to only anime.

Platform: Web
Browser: Chrome, Firefox, Brave
Version: No idea

Review the search algorithm or API endpoint responsible for retrieving data from the respective categories.
Test search functionality across all supported categories to ensure consistent performance.

**Comment by SnoozeScript** [comment]
# Search Functionality in OtakuHaven

The search functionality in OtakuHaven is designed to provide results specific to the type of content you are exploring, leveraging different APIs to ensure accuracy and relevance. Here's a detailed breakdown:

## Anime and Manga
- These searches are powered by **Anilist's GraphQL API**, which is specifically built for anime and manga data.
- This API allows for complex queries tailored to the unique metadata associated with anime and manga, such as genres, studios, episodes, or chapters.

## Movies and TV Shows
- These categories rely on **TMDb (The Movie Database)**, a separate API that specializes in movie and television-related content.
- TMDb provides access to metadata like cast, crew, release dates, and ratings, optimized for visual media.

---

## Why the Search Isn’t Combined
- **Independent Systems**: Anilist and TMDb are distinct platforms with no shared datasets or integrations. Each one is optimized for its specific content type, making it impractical to merge their results directly.
- **Category-Specific Relevance**: By keeping the searches separate, the system ensures that users get results relevant to the category they are browsing.  
  For example, searching for "Naruto" in the anime section fetches detailed anime results from Anilist, while searching for "Naruto" in the movies section avoids irrelevant or mixed results.

---

## How It Works
- When you visit a specific section (e.g., anime, manga, movies, or TV shows), the search bar dynamically routes your query to the appropriate API endpoint.
- This ensures that the results you see are directly aligned with the type of content you’re currently exploring.
